add more outputs (ffwert,augsburg,freising)
freifunkMUC/ffmuc-salt-public pull request #154
Opened 2024-02-18 22:10 UTC by T0biii

2024-03-12 21:34 UTC, DasSkelett requested changes
Sorry for having a look at it only now. For Augsburg and Freising the sites must also be arrays, otherwise it complains. Apart from that, looks good.

2024-03-12 21:34 UTC, DasSkelett commented on yanic/yanic.conf.tmpl
> +sites = "ffmuc_augsburg"
```suggestion
sites = ["ffmuc_augsburg"]
```

2024-03-12 21:34 UTC, DasSkelett commented on yanic/yanic.conf.tmpl
> +sites = "ffmuc_freising"
```suggestion
sites = ["ffmuc_freising"]
```

2024-03-13 06:51 UTC, T0biii commented
atm https://map.ffmuc.net/data/meshviewer-ffdon.json is empty. 
does it have anything to do with this change?

2024-03-14 19:32 UTC, DasSkelett approved these changes
Thanks, this should be good!

2024-03-14 19:33 UTC, merged