systemd-networkd: Update to v249
freifunkMUC/ffmuc-salt-public pull request #53
Opened 2021-07-26 16:09 UTC by krombel

2021-07-26 16:17 UTC, awlx requested changes

2021-07-26 16:17 UTC, awlx commented on systemd-networkd/files/systemd-netdev.jinja2
> -Local={{ salt['wireguard_v6.generate'](salt['pillar.get']('netbox:config_context:wireguard:public_key')) }}
I think local-ip needs to bet set.

2021-07-26 16:17 UTC, awlx commented on systemd-networkd/init.sls
> +{% set systemd_version = "249.164.gf571d9d5f0+20.04.20210724133612" %}
Can we only do this if it's a gateway?

2021-07-26 16:22 UTC, awlx commented
Nice :). Left some comments.

2021-07-26 16:39 UTC, awlx submitted a review, later dismissed
LGTM

2021-07-26 17:40 UTC, awlx requested changes

2021-07-26 17:40 UTC, awlx commented on systemd-networkd/files/batadv-throughput.sh
> +    echo Set throughput_override on $i
would add "" here.

2021-07-26 17:44 UTC, awlx commented on systemd-networkd/files/batadv-throughput.sh
> +    echo Set throughput_override on $i
```suggestion
    logger -t batadv-override  "Set throughput_override on $i"
```

2021-07-26 17:47 UTC, awlx requested changes

2021-07-26 17:47 UTC, awlx commented on systemd-networkd/files/batadv-throughput.sh
> +    echo "Set throughput_override on $i"
```suggestion
    logger -t batadv-override "Set throughput_override on $i"
```

2021-07-26 18:36 UTC, awlx approved these changes

2021-07-26 20:26 UTC, awlx commented on systemd-networkd/files/systemd-network.jinja2
> +MACAddress=00:00:00:00:00
```suggestion
MACAddress=00:00:00:00:00:00
```

Maybe it works with a valid mac :D. Whoops

2021-07-27 13:42 UTC, krombel commented
now as this ist tested in production I think it is finally safe to merge it :)

2021-07-27 13:43 UTC, awlx approved these changes
Closes #51 as well :)

2021-07-27 13:44 UTC, merged